### ISSUE TITLE
Unexpected input(s) 'root-directory',

### ISSUE THREAD

**Issue by ikenna** [42Crunch/api-security-audit-action#6]
I am using 
 

     -  name: "Run OpenAPI security audit"
        uses: 42Crunch/api-security-audit-action@v3
        with:
         api-token: ${{ secrets.CRUNCH_API_TOKEN }}
         min-score: 85
         root-directory: ./api-definitions

And I am getting 

> Warning: Unexpected input(s) 'root-directory', valid inputs are ['entryPoint', 'args', 'api-token', 'min-score', 'platform-url', 'log-level', 'share-everyone', 'github-token', 'upload-to-code-scanning', 'ignore-failures']

Am I using the root-directory attribute wrongly?

**Comment by ikenna** [comment]
I am also getting a similar error when I try to set 'default-collection-name'

**Comment by ak1394** [comment]
Thanks for reporting the issue! Looks like we're missing entries in the action manifest which lists allowed parameters. I'll update the action, and will comment in the issue once the update is available.

**Comment by ikenna** [comment]
Thank you for fixing it! Works 👍
